apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: ihebkhalfallah/mongo-demo:1
          ports:
            - containerPort: 8090
        - name: mongo
          image: mongo:4.2.2
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: NodePort  # Use NodePort to expose externally
---
