version: '3'
services:
  # MongoDB service
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: mongodb

  # Spring Boot application service
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile-spring
    ports:
      - "9090:9090"
    depends_on:
      - mongodb
