version: '3'
services:
  mongodb:
    image: mongo:latest
    port:
      - "27017:27017"
  eloquent_murdock:
    image: ihebkhalfallah/mongo-demo:1
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
