version: '3'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - mongodb-data:/data/db
  myapp:
    image: registry.hub.docker.com/ihebkhalfallah/mongo-demo:1
    ports:
      - "9091:9090"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://mongo:27017/gte3"
    networks:
      - backend

volumes:
  mongodb-data:

networks:
  backend:
