version: '3.3'

services:
  myapp:
    image: ihebkhalfallah/mongo-demo:1
    ports:
      - "9090:9090"
    networks:
      - mynetwork
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://mongo:27017/gte3"

  mongo:
    image: mongo:4.2.2
    hostname: mongo
    ports:
      - "27017:27017"
    networks:
      - mynetwork

networks:
  mynetwork:

