version: '3'
services:
  mongo-demo-app-service:
    image: ihebkhalfallah/mongo-demo:1
    ports:
      - "30081:8080"
    environment:
      - MONGO_DB=${MONGO_DB_SERVICE:-mongo-demo-db-service}
      - MONGO_HOST=${MONGO_DB_DATABASE:-gte3}
    depends_on:
      - mongo-demo-db-service

  mongo-demo-db:
    image: mongo:latest
    ports:
      - "27017:27017"

  mongo-demo-db-service:
    image: mongo:latest
    ports:
      - "27017:27017"

  mongo-demo-db-config:
    name: mongo-demo-db-config
    data:
      host: ${MONGO_DB_SERVICE:-mongo-demo-db-service}
      database: ${MONGO_DB_DATABASE:-gte3}
