apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-spring-boot-app
spec:
  replicas: 3  # Adjust the number of replicas based on your needs
  selector:
    matchLabels:
      app: your-spring-boot-app
  template:
    metadata:
      labels:
        app: your-spring-boot-app
    spec:
      containers:
      - name: your-spring-boot-app
        image: ihebkhalfallah/mongo-demo:1  # Replace with your Docker image name and version
        ports:
        - containerPort: 9090  # Specify the port your Spring Boot app is running on
        env:
        - name: SPRING_DATA_MONGODB_URI
          value: "mongodb://mongo:27017/gte3"  # Adjust based on your MongoDB connection details
